---
title: "碩一生活小調查"
output: github_document
---
# clean data
```{r, message=FALSE, warning=FALSE, include=FALSE}
#setwd("C:\\Users\\user\\Desktop\\workplace")
setwd("/Users/hsuwei/Desktop/workplace")
library(tidyverse)
library(labelled)
#life.df <- readxl::read_xlsx("lifesurvey.xlsx")
life.df <- read_csv("/Users/hsuwei/Desktop/workplace/lifesurvey.csv")
names(life.df)[2] <- "gender"
names(life.df)[4] <- "grade"
names(life.df)[5] <- "class_2"
names(life.df)[6] <- "class_1"
life.df <- life.df %>% arrange(grade)
life.df <- life.df[-c(1:3), ]
life.df[2] <- gsub("生理男", 1, life.df$gender)
life.df[2] <- gsub("生理女", 0, life.df$gender)

# 命名變項

renvar <- function(x){
    x <- gsub("週一的時間分配 - ", "Mon_", x)
    x <- gsub("週二的時間分配 - ", "Tue_", x)
    x <- gsub("週三的時間分配 - ", "Wen_", x)
    x <- gsub("週四的時間分配 - ", "Thu_", x)
    x <- gsub("週五的時間分配 - ", "Fri_", x)
    x <- gsub("週六的時間分配 - ", "Sat_", x)
    x <- gsub("週日的時間分配 - ", "Sun_", x)
  
    x <- gsub("修課時間", "studying", x)
    x <- gsub("助教工作時間", "ast", x)
    x <- gsub("上班時間", "job", x)
    x <- gsub("論文時間", "research", x)
    x <- gsub("重要他人時間", "company", x)
    x <- gsub("其他外務時間", "other", x)
    x <- gsub("睡眠時間", "sleeping", x)
    
    x
}
names(life.df)[1] <- "id"
var <- names(life.df)
var <- renvar(var)
names(life.df) <- var


# 加總
rsum <- function(x, y) {
  z <- x %>% rowwise() %>% select(contains(y)) %>% rowSums() 
  z    
}
    
life.df2 <- life.df %>%
    select( -contains("_1")) %>%
    mutate(studying = rsum(., "studying"),
           ast = rsum(., "ast"), 
           job = rsum(., "job"),
           research = rsum(., "research"),
           company = rsum(., "company"),
           other = rsum(., "other"),
           sleeping = rsum(., "sleeping"), 
           sem = 2)
life.df1 <- life.df %>%
    select(1:6, contains("_1")) %>%
    mutate(studying = rsum(., "studying"),
           ast = rsum(., "ast"), 
           job = rsum(., "job"),
           research = rsum(., "research"),
           company = rsum(., "company"),
           other = rsum(., "other"),
           sleeping = rsum(., "sleeping"),
           sem = 1)
life1.long <- life.df1 %>%
    select(1, 6, 57:64) %>%
    gather(key = perweek, value = hours, -c(id, class_1, sem))

life2.long <- life.df2 %>%
    select(1, 5, 62:69) %>%
    gather(key = perweek, value = hours, -c(id, class_2, sem))

    
```

---

# mapping tools 
```{r, echo=FALSE}
perweek.lab <- c("助教", "重要他人", "工作", "其他重要事物", "研究", "睡眠", "修課")

b1 <- life1.long %>%
    group_by(perweek) %>%
    summarise(hoursw = sum(hours)) %>%
    mutate(prop = hoursw / sum(hoursw), sem = "1")
b2 <- life2.long %>%
    group_by(perweek) %>%
    summarise(hoursw = sum(hours)) %>%
    mutate(prop = hoursw / sum(hoursw), sem = "2")

b12 <- bind_rows(b1, b2)

all <- inner_join(life.df1[,c(1:6,57:63)], life.df2[, c(1, 63:68)], by = "id", suffix = c(".1st", ".2nd"))
a12 <- bind_cols(b1, b2)
b12.long <- life1.long %>% rename(class_2 = class_1) %>%
  bind_rows(life2.long)
```

# 整體時間分配
```{r, echo=FALSE}
ggplot(b12.long, aes(perweek %>% as.factor(), hours, fill = perweek)) +
  geom_boxplot() +
  labs(title = "時間分配分佈", x = "時間安排項目", y = "小時") +
  scale_x_discrete(labels = perweek.lab) +
  scale_fill_discrete(name = "時間安排項目", labels = perweek.lab) +
  theme(text= element_text(family = "黑體-繁 中黑", size = 14))
```


可以由此看出各項目的分布狀況，修課時間是大家平均安排最多時間的項目，其中工作、其他和研究項目上都有較極端的
個案。

---

# 平均一周的時間分配
## 第一學期
```{r, echo=FALSE}
bar1 <- life1.long %>%
    group_by(perweek) %>%
    summarise(hoursw = sum(hours)) %>%
    mutate(prop = hoursw / sum(hoursw)) %>%
ggplot() +
    geom_bar(mapping = aes(x = perweek, y = prop, fill = perweek), stat = "identity")+
 labs(title = "第一學期每週時間安排", x = "時間安排項目", y = "prop") +
  scale_fill_discrete(name = "時間安排項目", labels = perweek.lab)+
  scale_x_discrete(labels = perweek.lab) +
  theme( text= element_text(family = "黑體-繁 中黑", size = 14))
bar1
```

---

```{r, echo=FALSE}
bar1 + coord_polar()
```

---

## 第二學期

```{r, echo=FALSE}
bar2 <- life2.long %>%
    group_by(perweek) %>%
    summarise(hoursw = sum(hours)) %>%
    mutate(prop = hoursw / sum(hoursw)) %>%
ggplot() +
  geom_bar(mapping = aes(x = perweek, y = prop, fill = perweek), stat = "identity")+
  labs(title = "第二學期每週時間安排", x = "時間安排項目", y = "prop") +
  scale_fill_discrete(name = "時間安排項目", labels = perweek.lab)+
  scale_x_discrete(labels = perweek.lab) +
  theme( text= element_text(family = "黑體-繁 中黑", size = 14))
bar2
```

---

```{r, echo=FALSE}
bar2 + coord_polar()
```

---

# 兩學期比較
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(b12) +
  geom_bar(mapping = aes(x = perweek, y = prop, fill = sem), stat = "identity", position = "dodge") +
  labs(title = "兩學期時間安排比較", x = "時間安排項目", y = "prop") +
  scale_fill_discrete(name = "學期")+
  scale_x_discrete(labels = perweek.lab) +
  theme( text= element_text(family = "黑體-繁 中黑", size = 14))
```


兩個學期比較起來，並沒有明顯的差別。

---

# 各學分組比較
```{r, echo=FALSE}
b12.long %>% 
  mutate(class_2 = ifelse(class_2 == 0, 3, class_2)) %>%
  set_value_labels(class_2 = c("under 3" = 3)) %>%
  mutate(class_2 = to_factor(class_2)) %>%
ggplot() +
    geom_bar(mapping = aes(x = perweek, y = hours, fill = perweek %>% as.factor()), stat = "identity",
             position = "dodge") +
  labs(title = "各學分組每週時間安排", x = "時間安排項目", y = "小時") +
  facet_grid(~ class_2) +
  theme(axis.text.x = element_blank()) +
  scale_fill_discrete(name = "時間安排項目", labels = c("助教", "重要他人", "工作", "其他重要事物", "研究", "睡眠", "修課"))+
  theme(text= element_text(family = "黑體-繁 中黑", size = 14))
```

細分修課學分來看，將0學分和3學分合併，較明顯的可以發現修課時間增加會壓縮到工作的時間。

---

# 個人狀況(不公布)
```{r, eval=FALSE, include=FALSE}
b12.long %>%
 distinct(id, sem) %>%
 mutate(number = c(seq(1:24))) %>%
 right_join(b12.long, by = c("id", "sem")) %>%
  mutate(class_2 = ifelse(class_2 == 0, 3, class_2)) %>%
  set_value_labels(class_2 = c("under 3" = 3)) %>%
  mutate(class_2 = to_factor(class_2)) %>%  
  ggplot() +
    geom_bar(mapping = aes(x = number %>% as.factor(), y = hours, fill = perweek), stat = "identity") +
  facet_grid(~ class_2, scales = "free_x") +
  labs(title = "各學分組每週時間安排", x = "個人狀況", y = "小時") +
  theme(axis.text.x = element_blank()) +
  scale_fill_discrete(name = "時間安排項目", labels = c("助教", "重要他人", "工作", "其他重要事物", "研究", "睡眠", "修課"))+
  theme(text= element_text(family = "黑體-繁 中黑", size = 14))
```

細分為個人的時間安排來看，修課時間是主要的時間安排，但修課的學分數並不必然排擠到從事研究的時間，但同時可能會壓縮到陪伴或從事其他事物的時間。

---

# 高研究時間組
```{r, echo=FALSE}
p1 <-  b12.long %>%
  filter(perweek == "research") %>%
  arrange(desc(hours)) %>%
  mutate(res_rank = seq(1:24)) %>%
  select(id, sem, res_rank) %>%
  right_join(b12.long, by = c("id", "sem")) %>%
  filter(res_rank <= 3) %>%
  ggplot() +
  geom_bar(mapping = aes(x = res_rank %>% as.factor(), y = hours, fill = perweek), stat = "identity",
           width = 0.55) +
  labs(title = "研究時數較高組", x = "個人狀況", y = "小時") +
  theme(axis.text.x = element_blank()) +
  scale_fill_discrete(guide = F)+
  theme(text= element_text(family = "黑體-繁 中黑", size = 14))

p2 <- b12.long %>%
  filter(perweek == "research") %>%
  arrange(desc(hours)) %>%
  mutate(res_rank = seq(1:24)) %>%
  select(id, sem, res_rank) %>%
  right_join(b12.long, by = c("id", "sem")) %>%
  filter(res_rank >= 22) %>%
  ggplot() +
  geom_bar(mapping = aes(x = res_rank %>% as.factor(), y = hours, fill = perweek), stat = "identity") +
  labs(title = "研究時數較低組", x = "個人狀況", y = "小時") +
  theme(axis.text.x = element_blank()) +
  scale_fill_discrete(name = "時間安排項目", labels = c("助教", "重要他人", "工作", "其他重要事物", "研究", "睡眠", "修課"))+
  theme(text= element_text(family = "黑體-繁 中黑", size = 14))
gridExtra::grid.arrange(p1, p2, nrow = 1, ncol = 2)

```

若是希望能增加研究時間，則可能得犧牲工作時數，以及從事其他事物的時間，同時能負擔修課的時間也減少。

---






